/*
 * File: ListChooserPanel.java
 * Project: TRminator
 * Author: Jeff Houle
 */
package trminator;

import java.util.List;
import javax.swing.JDialog;

/**
 * ListChooserPanel is intended to be used within a dialog.
 * The dialog is to be known by this panel, so that it can be turned off by the panel.
 * It is used to present the user with choices, in a list.
 * Only one item can be chosen. Clicking OK changes the offical chosen value to the one the user chose.
 * Clicking Cancel will make it the original value.
 * It was designed for use with ThreepioFrame, but can be used for anything.
 * @author Jhoule
 * @see TRminatorGUI
 */
public class ListChooserPanel extends javax.swing.JPanel
{

    String chosenValue, originalValue;
    JDialog dialog;

    /**
     * Creates a new ListChooserPanel, with supplied info.
     * @param vals - the values (as strings) to list.
     * @param orig - the original or default value.
     * @param dia - the dialog that this is associated with.
     */
    public ListChooserPanel(List<String> vals, String orig, JDialog dia)
    {
        initComponents();

        dialog = dia;
        dialog.setSize(this.getSize());


        originalValue = orig;
        lstModels.setListData(vals.toArray());
        lstModels.setSelectedValue(originalValue, true);
    }

    /**
     * returns the value chosen either by choice or defualt.
     * if the choosing process never occurred, or the dialog was exited,
     * this value can (and will) be NULL.
     * @return the chosen value, as specified in description.
     */
    public String getChosenValue()
    {
        return chosenValue;
    }

    /**
     * sets the chosen value, then closes the dialog box.
     * @param str - the string to set the chosen val to.
     */
    private void finish(String str)
    {
        chosenValue = str;

        dialog.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstModels = new javax.swing.JList();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(176, 161));
        setMinimumSize(new java.awt.Dimension(176, 161));

        lstModels.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstModels.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstModels);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * when the OK button is pressed, process everything, using the user's choice.
     * @param evt - the event of the click
     */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOKActionPerformed
    {//GEN-HEADEREND:event_btnOKActionPerformed
        finish((String) lstModels.getSelectedValue());
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * when the Cancel button is pressed, process everything, ignoring anything
     * the user has one.
     * @param evt - the event of the mouse click.
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        finish(originalValue);
    }//GEN-LAST:event_btnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstModels;
    // End of variables declaration//GEN-END:variables
}
