/*
 * File: TRminatorGUIPanel.java
 * Project: TRminator
 * Author: Jeff Houle
 *
 */
package trminator;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import threepio.filehandling.FileIntake;
import threepio.tabler.container.ColumnMap;

/**
 * TRminatorGUIPanel is the face of the TRmiantor GUI.
 * It's where user I/O occurs.
 * @author jhoule
 * @see TRminatorGUI
 */
public class TRminatorGUIPanel extends javax.swing.JFrame
{

    protected boolean loaded;

    /**
     * flag for producing debug output
     */
    private boolean debugMode = false;
    /**
     * Columns mapped to the "attributes" of objects/parameters they list.
     */
    protected ColumnMap cols;
    protected TRminatorGUI gui;

    /**
     * Creates new TRminatorGUIPanel form.
     * auto-fills the column map, which is user-editable.
     * @param aGui - the GUI this panel runs on top of.
     */
    public TRminatorGUIPanel(TRminatorGUI aGui)
    {
        gui = aGui;
        initComponents();

        this.setTitle("TRminator");
        lblVersion.setText(TRminatorApp.appVersion);

        loaded = false;

        // lblVersion.setText(appVersion);
        // clearFields(true);
        // cols = gui.getCols();
        // updateFormForMode();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpMode = new javax.swing.ButtonGroup();
        diaOptions = new javax.swing.JDialog();
        pnlInput0 = new javax.swing.JPanel();
        pnlInput2 = new javax.swing.JPanel();
        pnlModel2 = new javax.swing.JPanel();
        lblModel2 = new javax.swing.JLabel();
        txtModelName2 = new javax.swing.JTextField();
        txtFileIn2 = new javax.swing.JTextField();
        lblInFile2 = new javax.swing.JLabel();
        btnInBrowse2 = new javax.swing.JButton();
        pnlInput1 = new javax.swing.JPanel();
        pnlModel1 = new javax.swing.JPanel();
        lblModel1 = new javax.swing.JLabel();
        txtModelName1 = new javax.swing.JTextField();
        btnInBrowse1 = new javax.swing.JButton();
        txtFileIn1 = new javax.swing.JTextField();
        lblInFile1 = new javax.swing.JLabel();
        lblDir = new javax.swing.JLabel();
        lblDirName = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        lblContainerName = new javax.swing.JLabel();
        txtContainerName = new javax.swing.JTextField();
        pnlOptions = new javax.swing.JPanel();
        chkDiff = new javax.swing.JCheckBox();
        chkProfiles = new javax.swing.JCheckBox();
        chkLooks = new javax.swing.JCheckBox();
        pnlOut = new javax.swing.JPanel();
        btnOutBrowse = new javax.swing.JButton();
        txtFileOut = new javax.swing.JTextField();
        lblOutFile = new javax.swing.JLabel();
        pnlMode = new javax.swing.JPanel();
        radVDT = new javax.swing.JRadioButton();
        radGXT = new javax.swing.JRadioButton();
        radNSDDT = new javax.swing.JRadioButton();
        btnGo = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblVersion = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStatus = new javax.swing.JTextArea();
        menuBarMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuBtnChangeDir = new javax.swing.JMenuItem();
        mnuBtnExit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        munuEditCols = new javax.swing.JMenuItem();
        munLoadCols = new javax.swing.JMenuItem();

        diaOptions.setAlwaysOnTop(true);
        diaOptions.setMinimumSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout diaOptionsLayout = new javax.swing.GroupLayout(diaOptions.getContentPane());
        diaOptions.getContentPane().setLayout(diaOptionsLayout);
        diaOptionsLayout.setHorizontalGroup(
            diaOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        diaOptionsLayout.setVerticalGroup(
            diaOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlInput2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12))); // NOI18N
        pnlInput2.setEnabled(false);

        lblModel2.setFont(new java.awt.Font("Arial", 1, 14));
        lblModel2.setText("Model:");

        txtModelName2.setEditable(false);

        javax.swing.GroupLayout pnlModel2Layout = new javax.swing.GroupLayout(pnlModel2);
        pnlModel2.setLayout(pnlModel2Layout);
        pnlModel2Layout.setHorizontalGroup(
            pnlModel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModel2Layout.createSequentialGroup()
                .addComponent(lblModel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelName2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(95, 95, 95))
        );
        pnlModel2Layout.setVerticalGroup(
            pnlModel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblModel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtModelName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtFileIn2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFileIn2PropertyChange(evt);
            }
        });
        txtFileIn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFileIn2KeyTyped(evt);
            }
        });

        lblInFile2.setFont(new java.awt.Font("Arial", 1, 14));
        lblInFile2.setText("File:");

        btnInBrowse2.setText("Browse...");
        btnInBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInBrowse2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInput2Layout = new javax.swing.GroupLayout(pnlInput2);
        pnlInput2.setLayout(pnlInput2Layout);
        pnlInput2Layout.setHorizontalGroup(
            pnlInput2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInput2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInput2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInput2Layout.createSequentialGroup()
                        .addComponent(pnlModel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInput2Layout.createSequentialGroup()
                        .addComponent(lblInFile2)
                        .addGap(36, 36, 36)
                        .addComponent(txtFileIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInBrowse2)
                        .addGap(28, 28, 28))))
        );
        pnlInput2Layout.setVerticalGroup(
            pnlInput2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInput2Layout.createSequentialGroup()
                .addGroup(pnlInput2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileIn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInBrowse2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlModel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlInput1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12))); // NOI18N

        lblModel1.setFont(new java.awt.Font("Arial", 1, 14));
        lblModel1.setLabelFor(lblModel1);
        lblModel1.setText("Model:");

        txtModelName1.setEditable(false);

        javax.swing.GroupLayout pnlModel1Layout = new javax.swing.GroupLayout(pnlModel1);
        pnlModel1.setLayout(pnlModel1Layout);
        pnlModel1Layout.setHorizontalGroup(
            pnlModel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblModel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnlModel1Layout.setVerticalGroup(
            pnlModel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtModelName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblModel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnInBrowse1.setText("Browse...");
        btnInBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInBrowse1ActionPerformed(evt);
            }
        });

        txtFileIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileIn1ActionPerformed(evt);
            }
        });
        txtFileIn1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFileIn1PropertyChange(evt);
            }
        });
        txtFileIn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFileIn1KeyTyped(evt);
            }
        });

        lblInFile1.setFont(new java.awt.Font("Arial", 1, 14));
        lblInFile1.setLabelFor(lblInFile1);
        lblInFile1.setText("File:");

        lblDir.setFont(new java.awt.Font("Arial", 1, 14));
        lblDir.setLabelFor(lblDirName);
        lblDir.setText("Working Directory:");

        lblDirName.setFont(new java.awt.Font("Arial", 0, 14));
        lblDirName.setForeground(new java.awt.Color(255, 51, 51));
        lblDirName.setText("<Directory>");

        javax.swing.GroupLayout pnlInput1Layout = new javax.swing.GroupLayout(pnlInput1);
        pnlInput1.setLayout(pnlInput1Layout);
        pnlInput1Layout.setHorizontalGroup(
            pnlInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInput1Layout.createSequentialGroup()
                        .addComponent(lblInFile1)
                        .addGap(36, 36, 36)
                        .addComponent(txtFileIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInBrowse1))
                    .addGroup(pnlInput1Layout.createSequentialGroup()
                        .addComponent(lblDir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDirName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlModel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlInput1Layout.setVerticalGroup(
            pnlInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInput1Layout.createSequentialGroup()
                .addGroup(pnlInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDirName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlModel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XML Container", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        pnlContainer.setEnabled(false);

        lblContainerName.setFont(new java.awt.Font("Arial", 1, 14));
        lblContainerName.setLabelFor(txtContainerName);
        lblContainerName.setText("Name:");

        txtContainerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContainerNameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContainerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContainerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Misc. Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        chkDiff.setFont(new java.awt.Font("Arial", 1, 12));
        chkDiff.setSelected(true);
        chkDiff.setText("Diff final two tables");
        chkDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDiffActionPerformed(evt);
            }
        });

        chkProfiles.setFont(new java.awt.Font("Arial", 1, 12));
        chkProfiles.setText("Include profile table");
        chkProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProfilesActionPerformed(evt);
            }
        });

        chkLooks.setFont(new java.awt.Font("Arial", 1, 12));
        chkLooks.setSelected(true);
        chkLooks.setText("Format cells to fixed width");

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions);
        pnlOptions.setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDiff)
                    .addComponent(chkProfiles)
                    .addComponent(chkLooks))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkDiff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkProfiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkLooks))
        );

        javax.swing.GroupLayout pnlInput0Layout = new javax.swing.GroupLayout(pnlInput0);
        pnlInput0.setLayout(pnlInput0Layout);
        pnlInput0Layout.setHorizontalGroup(
            pnlInput0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInput0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInput0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlOptions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInput2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(pnlInput1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlInput0Layout.setVerticalGroup(
            pnlInput0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInput0Layout.createSequentialGroup()
                .addComponent(pnlInput1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlOut.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12))); // NOI18N

        btnOutBrowse.setText("Browse...");
        btnOutBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutBrowseActionPerformed(evt);
            }
        });

        txtFileOut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFileOutPropertyChange(evt);
            }
        });
        txtFileOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFileOutKeyTyped(evt);
            }
        });

        lblOutFile.setFont(new java.awt.Font("Arial", 1, 14));
        lblOutFile.setLabelFor(txtFileOut);
        lblOutFile.setText("File:");

        javax.swing.GroupLayout pnlOutLayout = new javax.swing.GroupLayout(pnlOut);
        pnlOut.setLayout(pnlOutLayout);
        pnlOutLayout.setHorizontalGroup(
            pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblOutFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFileOut, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOutBrowse))
        );
        pnlOutLayout.setVerticalGroup(
            pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutFile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOutBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlMode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        btnGrpMode.add(radVDT);
        radVDT.setSelected(true);
        radVDT.setText("Versioned Document -> Table");
        radVDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radVDTActionPerformed(evt);
            }
        });

        btnGrpMode.add(radGXT);
        radGXT.setText("General XML - > Table");
        radGXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radGXTActionPerformed(evt);
            }
        });

        btnGrpMode.add(radNSDDT);
        radNSDDT.setText("Non-Sequential Documents -> Diff Table");
        radNSDDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNSDDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModeLayout = new javax.swing.GroupLayout(pnlMode);
        pnlMode.setLayout(pnlModeLayout);
        pnlModeLayout.setHorizontalGroup(
            pnlModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModeLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnlModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radGXT)
                    .addComponent(radNSDDT)
                    .addComponent(radVDT))
                .addContainerGap())
        );
        pnlModeLayout.setVerticalGroup(
            pnlModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModeLayout.createSequentialGroup()
                .addComponent(radVDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radGXT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(radNSDDT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGo.setFont(new java.awt.Font("Arial", 1, 24));
        btnGo.setText("GO");
        btnGo.setEnabled(false);
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trminator/img/iol_neon_TR.jpg"))); // NOI18N
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblVersion.setText("TRminator Version");

        btnLoad.setFont(new java.awt.Font("Arial", 1, 24));
        btnLoad.setText("Load Model");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        txtStatus.setBackground(javax.swing.UIManager.getDefaults().getColor("TextArea.disabledBackground"));
        txtStatus.setColumns(20);
        txtStatus.setEditable(false);
        txtStatus.setRows(2);
        jScrollPane1.setViewportView(txtStatus);

        mnuFile.setText("File");

        mnuBtnChangeDir.setText("Change Working Directory");
        mnuBtnChangeDir.setEnabled(false);
        mnuFile.add(mnuBtnChangeDir);

        mnuBtnExit.setText("Exit");
        mnuBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBtnExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuBtnExit);

        menuBarMain.add(mnuFile);

        mnuEdit.setText("Edit");

        munuEditCols.setText("change cols");
        munuEditCols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munuEditColsActionPerformed(evt);
            }
        });
        mnuEdit.add(munuEditCols);

        munLoadCols.setText("load cols");
        munLoadCols.setEnabled(false);
        munLoadCols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munLoadColsActionPerformed(evt);
            }
        });
        mnuEdit.add(munLoadCols);

        menuBarMain.add(mnuEdit);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblLogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInput0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))
                    .addComponent(lblVersion))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlInput0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pnlMode, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLogo))
                                .addGap(27, 27, 27)
                                .addComponent(pnlOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(lblVersion))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * when the go button is clicked, the process selected by the user is carried out.
     * @param evt - the event.
     */
    private void btnGoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGoActionPerformed
    {//GEN-HEADEREND:event_btnGoActionPerformed
        gui.makeTable();
    }//GEN-LAST:event_btnGoActionPerformed

    /**
     * When the button for browsing for an output file is clicked,
     * the filechooser launches to find a save path, and the UI
     * is updated for that.
     * @param evt - the ActionEvent of the click.
     */
    private void btnOutBrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOutBrowseActionPerformed
    {//GEN-HEADEREND:event_btnOutBrowseActionPerformed
        useFileChooserForField(txtFileOut, false, new File(txtFileIn1.getText()).getParentFile());

        gui.setOutputPath(txtFileOut.getText());
    }//GEN-LAST:event_btnOutBrowseActionPerformed

    /**
     * When the user clicks "browse" on the first input,
     * the filechooser is launched, changing the first file path.
     * @param evt - the ActionEvent of the click.
     */
    private void btnInBrowse1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnInBrowse1ActionPerformed
    {//GEN-HEADEREND:event_btnInBrowse1ActionPerformed
        useFileChooserForField(txtFileIn1, true, new File(txtFileIn1.getText()).getParentFile());
        gui.setInputPathOne(txtFileIn1.getText());
    }//GEN-LAST:event_btnInBrowse1ActionPerformed

    /**
     * When the user clicks "browse" on the second input,
     * the filechooser is launched, changing the second file path.
     * @param evt - the ActionEvent of the click.
     */
    private void btnInBrowse2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnInBrowse2ActionPerformed
    {//GEN-HEADEREND:event_btnInBrowse2ActionPerformed
        useFileChooserForField(txtFileIn2, true, new File(txtFileIn1.getText()).getParentFile());
        gui.setInputPathTwo(txtFileIn2.getText());
    }//GEN-LAST:event_btnInBrowse2ActionPerformed

    /**
     * When the load button is pressed, the user's input is checked,
     * and the GO button is enabled based on the check.
     * @param evt - the ActionEvent of the click.
     */
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLoadActionPerformed
    {//GEN-HEADEREND:event_btnLoadActionPerformed
        btnGo.setEnabled(gui.loadFiles() && ! txtFileOut.getText().isEmpty());
        
}//GEN-LAST:event_btnLoadActionPerformed

    /**
     * disables the Go button, because the user is modifying something.
     * @param evt - the ActionEvent of the modification.
     */
    private void txtFileIn2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFileIn2KeyTyped
    {//GEN-HEADEREND:event_txtFileIn2KeyTyped
        fileChanging();
    }//GEN-LAST:event_txtFileIn2KeyTyped

    /**
     * disables the Go button, because the user is modifying something.
     * @param evt - the ActionEvent of the modification.
     */
    private void txtContainerNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtContainerNameKeyTyped
    {//GEN-HEADEREND:event_txtContainerNameKeyTyped
        setGoButton();
    }//GEN-LAST:event_txtContainerNameKeyTyped

    /**
     * disables the Go button, because the user is modifying something.
     * @param evt - the ActionEvent of the modification.
     */
    private void txtFileOutKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFileOutKeyTyped
    {//GEN-HEADEREND:event_txtFileOutKeyTyped
        setGoButton();
    }//GEN-LAST:event_txtFileOutKeyTyped

    /**
     * debug only: does something when the logo is clicked.
     *
     * @param evt - the ActionEvent of the click.
     */
    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblLogoMouseClicked
    {//GEN-HEADEREND:event_lblLogoMouseClicked
        magic();
    }//GEN-LAST:event_lblLogoMouseClicked

    /**
     * picks up a click of a change model button for input #1,
     * and updates the form for that.
     * @param evt - the ActionEvent of the click
     */
    private void munuEditColsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_munuEditColsActionPerformed
    {//GEN-HEADEREND:event_munuEditColsActionPerformed

        IHMEditPanel pnlCol = new IHMEditPanel(cols, "Column Name", "XML Value");

        pnlCol.setVisible(true);
        diaOptions = new JDialog();
        diaOptions.setContentPane(pnlCol);
        diaOptions.setSize(500, 300);
        diaOptions.setVisible(true);
    }//GEN-LAST:event_munuEditColsActionPerformed

    /**
     * exits the program when the user clicks Exit on the file menu.
     * @param evt - the event for the click
     */
    private void mnuBtnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuBtnExitActionPerformed
    {//GEN-HEADEREND:event_mnuBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuBtnExitActionPerformed

    /**
     * Changes the output box based on an option change.
     * @param evt - the event of the option change.
     */
    private void chkDiffActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkDiffActionPerformed
    {//GEN-HEADEREND:event_chkDiffActionPerformed
        if (btnGo.isEnabled())
        {
            txtStatus.setText("File(s) loaded\nclick GO to reprocess with new options");
        } else
        {
            txtStatus.setText("New options are in effect.");
        }
    }//GEN-LAST:event_chkDiffActionPerformed

    /**
     * does form stuff when a change occurs in the input field.
     * @param evt - the event of the change.
     */
    private void txtFileIn1PropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_txtFileIn1PropertyChange
    {//GEN-HEADEREND:event_txtFileIn1PropertyChange
        fileChanging();
    }//GEN-LAST:event_txtFileIn1PropertyChange

    /**
     * does form stuff when a change occurs in the input field.
     * @param evt - the event of the change.
     */
    private void txtFileIn1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFileIn1KeyTyped
    {//GEN-HEADEREND:event_txtFileIn1KeyTyped
        fileChanging();
    }//GEN-LAST:event_txtFileIn1KeyTyped

    /**
     * does form stuff when a change occurs in the input field.
     * @param evt - the event of the change.
     */
    private void txtFileIn2PropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_txtFileIn2PropertyChange
    {//GEN-HEADEREND:event_txtFileIn2PropertyChange
        fileChanging();
    }//GEN-LAST:event_txtFileIn2PropertyChange

    /**
     * Changes the mode, becasue the mode radio button has been changed.
     * @param evt - the event of the change.
     */
    private void radVDTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radVDTActionPerformed
    {//GEN-HEADEREND:event_radVDTActionPerformed
        updateFormForMode();
    }//GEN-LAST:event_radVDTActionPerformed

    /**
     * Changes the mode, becasue the mode radio button has been changed.
     * @param evt - the event of the change.
     */
    private void radGXTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radGXTActionPerformed
    {//GEN-HEADEREND:event_radGXTActionPerformed
        updateFormForMode();
    }//GEN-LAST:event_radGXTActionPerformed

    /**
     * Changes the mode, becasue the mode radio button has been changed.
     * @param evt - the event of the change.
     */
    private void radNSDDTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radNSDDTActionPerformed
    {//GEN-HEADEREND:event_radNSDDTActionPerformed
        updateFormForMode();
    }//GEN-LAST:event_radNSDDTActionPerformed

    private void chkProfilesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkProfilesActionPerformed
    {//GEN-HEADEREND:event_chkProfilesActionPerformed
        if (btnGo.isEnabled())
        {
            txtStatus.setText("File(s) loaded\nclick GO to reprocess with new options");
        } else
        {
            txtStatus.setText("New options are in effect.");
        }
    }//GEN-LAST:event_chkProfilesActionPerformed

    /**
     * loads a filechooser for the columns file.
     * @param evt - the event of this happening.
     */
    private void munLoadColsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_munLoadColsActionPerformed
    {//GEN-HEADEREND:event_munLoadColsActionPerformed
    }//GEN-LAST:event_munLoadColsActionPerformed

    private void txtFileIn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtFileIn1ActionPerformed
    {//GEN-HEADEREND:event_txtFileIn1ActionPerformed
        fileChanging();
    }//GEN-LAST:event_txtFileIn1ActionPerformed

    private void txtFileOutPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_txtFileOutPropertyChange
    {//GEN-HEADEREND:event_txtFileOutPropertyChange
        setGoButton();
    }//GEN-LAST:event_txtFileOutPropertyChange

    /**
     * called when a file input field is changing, to keep the user from running
     * the main function when their input is not good.
     */
    private void fileChanging()
    {
        gui.updateVariables();
        setLoadButton();
        setGoButton();
    }

    /**
     * DEBUGGING ONLY: fills in some fields for faster debugging.
     */
    private void magic()
    {
        String f1 = null, f2 = null;
        boolean diff = true;

        if (debugMode)
        {
            switch (getMode())
            {
                case 0:

                    f1 = "c:\\testing\\xml\\tr-098-1-2-0.xml";

                    break;
                case 1:

                    break;
                case 2:
                    f1 = "c:\\testing\\xml\\tr-098-1-2-0.xml";
                    f2 = "c:\\testing\\xml\\tr-098-1-0.xml";

                    break;
            }

            txtFileIn1.setText(f1);
            txtFileIn2.setText(f2);
            txtFileOut.setText("c:\\testing\\output.html");
            chkDiff.setSelected(diff);
        }
    }

    /**
     * pops up the file chooser for the user to use, then fills in the GUI field with the selected path.
     * @param field - the field that should be filled with the path
     * @param opening - set to true if opening, false if saving.
     * @param dir - the file or directory to start at
     */
    private void useFileChooserForField(JTextField field, boolean opening, File dir)
    {
        String path;
        File tempFile;

        setGoButton();

        tempFile = new File(field.getText());

        if (tempFile != null && tempFile.exists())
        {
            path = useFileChooser(opening, tempFile);
        } else
        {
            path = useFileChooser(opening, dir);
        }

        if (path != null)
        {
            field.setText(path);
        }

        field.updateUI();
    }

    /**
     * Pops up the file chooser for the user to use it, then returns the result.
     * If the user picks a valid file, the path is returned (and guaranteed to be a real path to a file).
     * Otherwise, a null pointer is returned.
     * @param opening - set to true if the user is opening a file, false if they are saving one.
     * @param startIn - a file or directory to start file selection from.
     * @return the path to the chosen file, if chosen. null otherwise.
     */
    private String useFileChooser(boolean opening, File startIn)
    {
        JFileChooser chooser = new JFileChooser();
        File f;

        if (startIn == null)
        {
            // open the file browser in execution directory.
            startIn = FileIntake.currentDir();
        }

        if (startIn != null && startIn.exists())
        {
            chooser.setSelectedFile(startIn);
        }

        if (opening)
        {
            chooser.showOpenDialog(this);
        } else
        {

            chooser.showSaveDialog(this);
        }

        f = chooser.getSelectedFile();

        if (f == null)
        {
            return null;
        }

        return f.getAbsolutePath();
    }

    /**
     * gets the number of the mode currently chosen.
     * @return the number of the mode.
     */
    @SuppressWarnings("empty-statement")
    private int getMode()
    {
        JRadioButton[] modes =
        {
            radVDT, radGXT, radNSDDT
        };

        int i;
        for (i = 0; i < modes.length && !modes[i].isSelected(); i++);

        // check for error.
        if (i == modes.length)
        {
            return -1;
        }

        return i;
    }

    protected void setLoadButton()
    {
        boolean file1NotEmpty = (!(txtFileIn1.getText().isEmpty()));
        switch (getMode())
        {
            case 2:
                btnLoad.setEnabled(!(file1NotEmpty
                        || txtFileIn2.getText().isEmpty()));
                break;
            default:
                btnLoad.setEnabled(file1NotEmpty);
                break;
        }

        loaded = false;
    }

    protected void setGoButton()
    {
        boolean temp = loaded && ! txtFileOut.getText().isEmpty();
        btnGo.setEnabled(temp);
        if (temp)
        {
            // if we can go, then we should make sure that the app pointers are up to date.
            gui.updateVariables();
        }
    }

    /**
     * Changes the form based on the user's selection of a new mode.
     */
    private void updateFormForMode()
    {
        //  clearFields(false);

        ArrayList<JComponent> on = new ArrayList<JComponent>(), off = new ArrayList<JComponent>();

        // always on:
        on.add(pnlInput0);
        on.add(pnlInput1);
        on.add(pnlMode);
        on.add(pnlOut);

        switch (getMode())
        {
            case 0:
                // on:
                on.add(pnlOptions);
                on.add(pnlModel1);
                on.add(chkDiff);
                on.add(chkProfiles);
                on.add(chkLooks);

                // off:
                off.add(pnlContainer);
                off.add(pnlInput2);

                btnLoad.setText("Load File");


                break;

            case 1:
                // on:
                on.add(pnlContainer);


                // off:
                off.add(pnlModel1);
                off.add(pnlInput2);
                off.add(pnlOptions);
                off.add(chkDiff);
                off.add(chkProfiles);
                off.add(chkLooks);

                btnLoad.setText("Load File");


                break;

            case 2:
                // on:
                on.add(pnlModel1);
                on.add(pnlInput2);
                on.add(chkLooks);

                // off:
                off.add(pnlOptions);
                off.add(pnlContainer);
                off.add(chkDiff);
                off.add(chkProfiles);

                btnLoad.setText("Load Files");



                break;

            default:
                System.err.println("unknown or bad mode");
                break;

        }

        // then do stuff based on the lists.

        for (int i = 0; i < off.size(); i++)
        {
            off.get(i).setVisible(false);
        }

        for (int j = 0; j < on.size(); j++)
        {
            on.get(j).setVisible(true);
        }

        setLoadButton();
    }

    /**
     * Pops up an error with the message for the user.
     * A default title is used.
     * @param msg - the message for the user.
     */
    protected void popupError(String msg)
    {
        JOptionPane.showMessageDialog(this, msg, "Application Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Pops up an error with the message for the user.
     * @param msg - the message for the user.
     * @param title - the title of the window.
     */
    protected void popupError(String msg, String title)
    {
        JOptionPane.showMessageDialog(this, msg, title, JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Sets the output path text
     * @param path - the text to set the output path to.
     */
    protected void setOutputPath(String path)
    {
        txtFileOut.setText(path);
    }

    /**
     * gets the output path text
     * @return the output path text.
     */
    protected String getOutputPath()
    {
        return txtFileOut.getText();
    }

    /**
     * sets the first input path text
     * @param path - the string to set the first input path to.
     */
    protected void setInputPathOne(String path)
    {
        txtFileIn1.setText(path);
    }

    /**
     * gets the first input path text.
     * @return the first input path
     */
    protected String getInputPathOne()
    {
        return txtFileIn1.getText();
    }

    /**
     * sets the second input path text
     * @param path - the string to set the second input path to.
     */
    protected void setInputPathTwo(String path)
    {
        txtFileIn2.setText(path);
    }

    /**
     * gets the second input path text.
     * @return the second input path
     */
    protected String getInputPathTwo()
    {
        return txtFileIn2.getText();
    }

    /**
     * sets the checkbox for diffing.
     * @param diff - if true, box is checked. unchecked otherwise.
     */
    protected void setDiffing(boolean diff)
    {
        chkDiff.setSelected(diff);
    }

    /**
     * gets the state of the checkbox for diffing.
     * @return true iff the box is checked, false otherwise.
     */
    protected boolean getDiffing()
    {
        return chkDiff.isSelected();
    }

    /**
     * sets the checkbox for looks.
     * @param looks - if true, box is checked. unchecked otherwise.
     */
    protected void setLooks(boolean looks)
    {
        chkLooks.setSelected(looks);
    }

    /**
     * gets the state of the checkbox for looks.
     * @return true iff the box is checked, false otherwise.
     */
    protected boolean getLooks()
    {
        return chkLooks.isSelected();
    }

    /**
     * sets the checkbox for profiles.
     * @param pro - if true, box is checked. unchecked otherwise.
     */
    protected void setDoProfiles(boolean pro)
    {
        chkProfiles.setSelected(pro);
    }

    /**
     * gets the state of the checkbox for profiles.
     * @return true iff the box is checked, false otherwise.
     */
    protected boolean getDoProfiles()
    {
        return chkProfiles.isSelected();
    }

    /**
     * Sets the text for the first model box.
     * @param m - the string to put in the box.
     */
    protected void setModel(String m)
    {
        txtModelName1.setText(m);
    }

    /**
     * Sets the text for the second model box.
     * @param m - the string to put in the box.
     */
    protected void setModelTwo(String m)
    {
        txtModelName2.setText(m);
    }

    /**
     * Sets the text for the container name box
     * @param s - the string to put in the box.
     */
    protected void setContainerName(String s)
    {
        txtContainerName.setText(s);
    }

    /**
     * gets the text in the container name box
     * @return the text in the box
     */
    protected String getContainerName()
    {
        return txtContainerName.getText();
    }

    /**
     * sets the text in the status box
     * @param s - the string to set the box text to.
     */
    protected void setStatus(String s)
    {
        txtStatus.setText(s);
    }
    
    protected String chooseFromList(String title, String msg, ArrayList<String> list)
    {
        int choice;
   
        choice = JOptionPane.showOptionDialog(this, msg , title, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, list.toArray(), 0);

        if (choice == JOptionPane.CLOSED_OPTION)
        {
            return null;
        }        

        return list.get(choice);
    }

    /**
     * Sets the mode:
     *      + 0 = Versioned document to table
     *      + 1 = General XML to table
     *      + 2 = nonsequential documents to diffed table
     * @param mode - the mode as defined in description.
     * @return true iff the mode changed, false iff not.
     * @throws Exception if the mode code is unrecognized.
     */
    protected boolean setMode(int mode) throws Exception
    {
        int prev = getMode(), cur = mode;
        switch (mode)
        {
            case 0:
            {
                radVDT.setEnabled(true);
                break;
            }

            case 1:
            {
                radGXT.setEnabled(true);
                break;
            }

            case 2:
            {
                radNSDDT.setEnabled(true);
                break;
            }

            default:
                throw new Exception("Bad mode: " + mode);
        }

        updateFormForMode();
        return (prev != cur);


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.ButtonGroup btnGrpMode;
    private javax.swing.JButton btnInBrowse1;
    private javax.swing.JButton btnInBrowse2;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnOutBrowse;
    private javax.swing.JCheckBox chkDiff;
    private javax.swing.JCheckBox chkLooks;
    private javax.swing.JCheckBox chkProfiles;
    private javax.swing.JDialog diaOptions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContainerName;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblDirName;
    private javax.swing.JLabel lblInFile1;
    private javax.swing.JLabel lblInFile2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblModel1;
    private javax.swing.JLabel lblModel2;
    private javax.swing.JLabel lblOutFile;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenuItem mnuBtnChangeDir;
    private javax.swing.JMenuItem mnuBtnExit;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem munLoadCols;
    private javax.swing.JMenuItem munuEditCols;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlInput0;
    private javax.swing.JPanel pnlInput1;
    private javax.swing.JPanel pnlInput2;
    private javax.swing.JPanel pnlMode;
    private javax.swing.JPanel pnlModel1;
    private javax.swing.JPanel pnlModel2;
    private javax.swing.JPanel pnlOptions;
    private javax.swing.JPanel pnlOut;
    private javax.swing.JRadioButton radGXT;
    private javax.swing.JRadioButton radNSDDT;
    private javax.swing.JRadioButton radVDT;
    private javax.swing.JTextField txtContainerName;
    private javax.swing.JTextField txtFileIn1;
    private javax.swing.JTextField txtFileIn2;
    private javax.swing.JTextField txtFileOut;
    private javax.swing.JTextField txtModelName1;
    private javax.swing.JTextField txtModelName2;
    private javax.swing.JTextArea txtStatus;
    // End of variables declaration//GEN-END:variables
}
